name: blog post ci

on:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Make post lists
      id: posts
      run: node .github/make-post-lists.js
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "lhr4884@naver.com"
        git config --global user.name "haryung-lee"
        git add -u
        git commit -m "Update recent post" || exit 0
        git push